---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-test-volume
  labels:
    app: hw06-jbolivar-test-redis
    env: test
    username: jbolivar
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
